import Config

# Runtime configuration — evaluated when the app starts, not at compile time
# This allows environment variables set by launchd/Salt to be read properly

# Load bot-specific config from file (generated by Salt at deployment time)
# This avoids the macOS launchd environment variable pass-through limitation
config_data = BotArmyLibraryRuntime.ConfigLoader.load_config()
Application.put_env(:bot_army_library_runtime, :config_data, config_data)

# Database configuration at runtime
# Priority: Config file > Environment variables > defaults
config :bot_army_job, BotArmyJobScheduler.Repo,
  database: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_JOB_DB_NAME", "ergon_job_scheduler"),
  hostname: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_JOB_DB_HOST", "localhost"),
  port:
    String.to_integer(BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_JOB_DB_PORT", "30003")),
  username: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_JOB_DB_USER", "postgres"),
  password: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_JOB_DB_PASSWORD", "postgres"),
  pool_size: String.to_integer(BotArmyLibraryRuntime.ConfigLoader.get("BOT_POOL_SIZE", "10")),
  ssl: false
