import Config

# Runtime configuration — evaluated when the app starts, not at compile time
# This allows environment variables set by launchd/Salt to be read properly

# Database configuration at runtime
# Priority: BOT_ARMY_JOB_DB_* (set by Salt/Jenkins) > DATABASE_* (from .env for local dev) > defaults
config :bot_army_job, BotArmyJobScheduler.Repo,
  database:
    System.get_env("BOT_ARMY_JOB_DB_NAME") || System.get_env("DATABASE_NAME") ||
      "ergon_job_scheduler",
  hostname:
    System.get_env("BOT_ARMY_JOB_DB_HOST") || System.get_env("DATABASE_HOST") || "localhost",
  port:
    String.to_integer(
      System.get_env("BOT_ARMY_JOB_DB_PORT") || System.get_env("DATABASE_PORT") || "30006"
    ),
  username:
    System.get_env("BOT_ARMY_JOB_DB_USER") || System.get_env("DATABASE_USER") || "postgres",
  password:
    System.get_env("BOT_ARMY_JOB_DB_PASSWORD") || System.get_env("DATABASE_PASSWORD") ||
      "postgres",
  pool_size: String.to_integer(System.get_env("BOT_POOL_SIZE") || "10"),
  ssl: false

# NATS configuration for bot_army_library_runtime — the library starts
# NATS.Connection with empty opts and its fail-safe default is the DEV broker
# (4223). Without this block the scheduler joins the wrong bus: every
# salt-seeded `nats request` job (companion.reflection, companion.heartbeat,
# youtube.scheduled.ingest, surface.discord.send, ...) fires on 4223 where
# nothing is subscribed and fails with :no_responders, while the fleet runs on
# 4222. Found 2026-09-12: every scheduled companion reflection since the fleet
# moved to air had failed this way. Same pattern as bot_army_companion /
# bot_army_llm / bot_army_sre / bot_army_deploy_pipeline runtime.exs.
if config_env() == :prod do
  # Load bot-specific config from file (generated by Salt at deployment time,
  # /etc/bot_army/job_scheduler.config.exs) — avoids the macOS launchd
  # environment variable pass-through limitation. Falls back to
  # System.get_env, then to the prod-safe default 4222.
  config_data = BotArmyLibraryRuntime.ConfigLoader.load_config()

  Application.put_env(:bot_army_library_runtime, :config_data, config_data)

  nats_host = BotArmyLibraryRuntime.ConfigLoader.get("NATS_HOST", "localhost")

  nats_port =
    BotArmyLibraryRuntime.ConfigLoader.get("NATS_PORT", "4222") |> String.to_integer()

  config :bot_army_library_runtime, :nats,
    servers: [{nats_host, nats_port}],
    ping_interval: 30_000,
    max_reconnect_attempts: 10,
    reconnect_delay_ms: 1000
end
